//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQTJobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.JobRequest = new HashSet<JobRequest>();
        }
    
        public int JobId { get; set; }
        public string Title { get; set; }
        public Nullable<int> CounterOfPost { get; set; }
        public string Description { get; set; }
        public string Experience { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<System.DateTime> DueToApply { get; set; }
        public string Salary { get; set; }
        public string JobType { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ProfessionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Skills { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Professions Professions { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRequest> JobRequest { get; set; }
    }
}
