//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQTJobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRequest
    {
        public int RequestId { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Profession { get; set; }
        public string Education { get; set; }
        public string MotivationLetter { get; set; }
        public string CvName { get; set; }
        public byte[] FileContent { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> JobSeekerId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual User User { get; set; }
    }
}
