//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQTJobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSeekerSkills
    {
        public Nullable<int> JobSeekerId { get; set; }
        public Nullable<int> SkillId { get; set; }
        public int JSS { get; set; }
    
        public virtual Skills Skills { get; set; }
        public virtual User User { get; set; }
    }
}
