//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQTJobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.JobSeekerSkills = new HashSet<JobSeekerSkills>();
            this.JobRequest = new HashSet<JobRequest>();
            this.Job = new HashSet<Job>();
        }
    
        public int SeekerId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string GraduationGrade { get; set; }
        public string Experience { get; set; }
        public string Cv { get; set; }
        public string Address { get; set; }
        public string Website { get; set; }
        public string ContactMail { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> TypeofProfessionId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual TypeofProfession TypeofProfession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSeekerSkills> JobSeekerSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRequest> JobRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Job { get; set; }
    }
}
